<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "post".
 *
 * @property int $id
 * @property int $user_id
 * @property string $title
 * @property string $preview
 * @property string $content
 * @property string $image
 * @property int $status
 * @property int $created_at
 * @property int $updated_at
 *
 * @property User $user
 */
class Post extends \yii\db\ActiveRecord
{
    use \backend\Traits\Seo;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'post';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        $arr = [
            [['user_id'], 'required'],
            [['user_id', 'status', 'created_at', 'updated_at'], 'integer'],
            [['preview', 'content'], 'string'],
            [['title', 'image'], 'string', 'max' => 255],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
        return array_merge($this->rulesSeo(), $arr);
    }


    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {

        $arr = [
            'id' => 'ID',
            'user_id' => 'User ID',
            'title' => 'Title',
            'preview' => 'Preview',
            'content' => 'Content',
            'image' => 'Image',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
        return array_merge($arr, $this->attributeLabelsSeo());
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }


    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        $this->afterSaveSeo();
    }

    public function beforeDelete()
    {
        $this->beforeDeleteSeo();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        parent::afterFind();
        $this->afterFindSeo();
    }
}
